# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: cli-kintone Test Automation

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: 'Platform'
        required: true
        default: 'ALL'
        options:
          - All
          - macos-latest
          - linux-latest
          - windows-latest
      releaseVersion:
        type: string
        description: 'Release version, Eg: v0.14.0'
        required: false

#  schedule:
#    - cron: '0 17 * * 1-5'

env:
  RELEASE_VERSION: ${{ github.event.inputs.releaseVersion }}
  DOMAIN: ${{ secrets.DOMAIN }}
  BASIC_DOMAIN: ${{ secrets.BASIC_DOMAIN }}
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  BASIC_USERNAME: ${{ secrets.BASIC_USERNAME }}
  BASIC_PASSWORD: ${{ secrets.BASIC_PASSWORD }}

jobs:
  handle-inputs:
    name: Handle parameters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: handle-parameter
        run: |
          platform="['${{ github.event.inputs.platform }}']"
          if [[ "${{ github.event.inputs.platform }}" == "All" ]]; then platform="['macos-latest','linux-latest','windows-latest']"; fi
          echo "::set-output name=platform::$platform"
          echo "PLATFORM=$platform" >> $GITHUB_ENV
          execution_message="RELEASE_VERSION:${{ github.event.inputs.releaseVersion }} - Platforms: $platform"
          echo "::notice title=Using workflow from branch::${GITHUB_REF##*/}"
          echo "::notice title=Test info::$execution_message"
    outputs:
      platform: ${{ steps.handle-parameter.outputs.platform }}

  test:
    name: ${{ matrix.platform }}
    needs: [ handle-inputs ]
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        platform: ${{ fromJSON(needs.handle-inputs.outputs.platform) }}
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 150

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
      - name: Install npm packages
        run: npm install
      - name: import test with --import option
        if: |
          !cancelled()
        run: npm run test src/tests/importWithOption
      - name: import test without --import option
        if: |
          !cancelled()
        run: npm run test src/tests/importWithoutOption
      - name: export test with --export option
        if: |
          !cancelled()
        run: npm run test src/tests/exportWithOption
      - name: export test without --export option
        if: |
          !cancelled()
        run: npm run test src/tests/exportWithoutOption