# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: cli-kintone Test Automation

on:
  push:
    branches: [ SSR-1064_test ]
  pull_request:
    branches: [ SSR-1064_test ]
  schedule:
    - cron: '0 3,9,15,21 * * *'
env:
  RELEASE_VERSION: ${{ secrets.RELEASE_VERSION }}
  DOMAIN: ${{ secrets.DOMAIN }}
  BASIC_DOMAIN: ${{ secrets.BASIC_DOMAIN }}
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  BASIC_USERNAME: ${{ secrets.BASIC_USERNAME }}
  BASIC_PASSWORD: ${{ secrets.BASIC_PASSWORD }}

jobs:
  test_mac:
    strategy:
      matrix:
        platform: [ macos-latest ]
        node-version: [ 12.16.3 ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: import test with --import option
        run: npm run test src/tests/importWithOption
      - name: import test without --import option
        run: npm run test src/tests/importWithoutOption
      - name: export test with --export option
        run: npm run test src/tests/exportWithOption
      - name: export test without --export option
        run: npm run test src/tests/exportWithoutOption
  test_linux:
    needs: test_mac
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node-version: [ 12.16.3 ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: import test with --import option
        run: npm run test src/tests/importWithOption
      - name: import test without --import option
        run: npm run test src/tests/importWithoutOption
      - name: export test with --export option
        run: npm run test src/tests/exportWithOption
      - name: export test without --export option
        run: npm run test src/tests/exportWithoutOption
  test_windows:
    needs: [ test_mac, test_linux ]
    strategy:
      matrix:
        platform: [ windows-latest ]
        node-version: [ 12.16.3 ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: import test with --import option
        run: npm run test src/tests/importWithOption
      - name: import test without --import option
        run: npm run test src/tests/importWithoutOption
      - name: export test with --export option
        run: npm run test src/tests/exportWithOption
      - name: export test without --export option
        run: npm run test src/tests/exportWithoutOption